---

- name: Install Hyprland
  community.general.pacman:
    name: "{{ hyprland_packages }}"
    state: present
    update_cache: true

- name: Install GPU-specific packages
  community.general.pacman:
    name: "{{ gpu_packages[ansible_facts['vendor'] | default('intel')] }}"
    state: present

- name: Install additional system packages
  community.general.pacman:
    name: "{{ additional_packages }}"
    state: present

- name: Ensure SDDM and qt6 are installed
  community.general.pacman:
    name:
      - sddm
      - qt6-svg
      - qt6-virtualkeyboard
      - qt6-multimedia-ffmpeg
    state: present

- name: Enable and start NetworkManager service
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true
    state: started

- name: Enable and start SDDM service
  ansible.builtin.systemd:
    name: sddm
    enabled: true
    state: started

- name: Enable seatd service for hardware access
  ansible.builtin.systemd:
    name: seatd
    enabled: true
    state: started

- name: Push out sddm.conf
  ansible.builtin.template:
    src: sddm.conf.j2
    dest: /etc/sddm.conf
    mode: "0644"
    owner: root
    group: root

- name: Check if /usr/share/sddm/themes/sddm-astronaut-theme exists
  ansible.builtin.stat:
    path: /usr/share/sddm/themes/sddm-astronaut-theme
  register: dir_check

- name: Perform action if directory exists
  ansible.builtin.debug:
    msg: "sddm-astronaut-theme already present."
  when: dir_check.stat.isdir

- name: Perform action if directory does not exist
  when: not dir_check.stat.isdir
  block:
    - name: Clone sddm-astronaut-theme repository
      ansible.builtin.git:
        repo: "https://github.com/JacobVHS/sddm-astronaut-theme"
        dest: "/usr/share/sddm/themes/sddm-astronaut-theme"
        version: "master"
        depth: 1
      become: true

    - name: Copy fonts from theme to system fonts directory
      ansible.builtin.copy:
        remote_src: true
        src: "/usr/share/sddm/themes/sddm-astronaut-theme/Fonts/"
        dest: "/usr/share/fonts/"
        owner: root
        group: root
        mode: "0755"
      become: true

- name: Ensure /etc/sddm.conf.d/ exists
  ansible.builtin.file:
    path: /etc/sddm.conf.d/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create SDDM virtual keyboard configuration
  ansible.builtin.copy:
    dest: "/etc/sddm.conf.d/virtualkbd.conf"
    content: |
      [General]
      InputMethod=qtvirtualkeyboard
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Push out the metadata.desktop
  ansible.builtin.template:
    src: metadata.desktop.j2
    dest: /usr/share/sddm/themes/sddm-astronaut-theme/metadata.desktop
    mode: "0644"
