---

- name: Push out pacman.conf
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf

- name: Make sure we are using Australian Pacman repo mirrors
  ansible.builtin.template:
    src: mirrorlist.j2
    dest: /etc/pacman.d/mirrorlist

- name: Run a pacman upgrade to sync current packages to latest
  community.general.pacman:
    upgrade: true
    update_cache: true

- name: Install required packages
  community.general.pacman:
    name: "{{ required_pacman_packages }}"
    state: present

- name: Get list of users in /home
  ansible.builtin.command: ls /home
  register: home_users

- name: Manage PARU for each user
  include_tasks: paru.yml
  loop: "{{ home_users.stdout_lines }}"
  loop_control:
    loop_var: user
